# Generated by Django 3.2.7 on 2021-09-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210928_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepost',
            name='catagory',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
